// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: message.proto

package team

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Message struct {
	Avatar               string   `protobuf:"bytes,1,opt,name=avatar,proto3" json:"avatar,omitempty"`
	FromUsername         string   `protobuf:"bytes,2,opt,name=fromUsername,proto3" json:"fromUsername,omitempty"`
	From                 string   `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,4,opt,name=to,proto3" json:"to,omitempty"`
	Content              string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ContentType          int32    `protobuf:"varint,6,opt,name=contentType,proto3" json:"contentType,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	MessageType          int32    `protobuf:"varint,8,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Url                  string   `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	FileSuffix           string   `protobuf:"bytes,10,opt,name=fileSuffix,proto3" json:"fileSuffix,omitempty"`
	File                 []byte   `protobuf:"bytes,11,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}
func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *Message) GetFromUsername() string {
	if m != nil {
		return m.FromUsername
	}
	return ""
}

func (m *Message) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Message) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Message) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Message) GetContentType() int32 {
	if m != nil {
		return m.ContentType
	}
	return 0
}

func (m *Message) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Message) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *Message) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Message) GetFileSuffix() string {
	if m != nil {
		return m.FileSuffix
	}
	return ""
}

func (m *Message) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "team.Message")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 215 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0xb6, 0xdb, 0xba, 0xb3, 0xab, 0xc8, 0x1c, 0x64, 0x4e, 0x12, 0xf6, 0xd4, 0x93,
	0x17, 0x9f, 0xc3, 0x4b, 0xd5, 0x07, 0x88, 0x32, 0x91, 0x42, 0xd3, 0x2c, 0xe9, 0x54, 0xf4, 0x71,
	0x7c, 0x53, 0xc9, 0xb4, 0x42, 0xbd, 0x7d, 0xff, 0xf7, 0xf3, 0x07, 0x26, 0x70, 0x1d, 0x79, 0x9a,
	0xfc, 0x07, 0x3f, 0x5c, 0x72, 0x92, 0x84, 0x95, 0xb0, 0x8f, 0xe7, 0x1f, 0x0b, 0xcd, 0xd3, 0xe2,
	0xf1, 0x0e, 0x6a, 0xff, 0xe9, 0xc5, 0x67, 0x32, 0xce, 0xb4, 0x87, 0x6e, 0x4d, 0x78, 0x86, 0x53,
	0xc8, 0x29, 0xbe, 0x4e, 0x9c, 0x47, 0x1f, 0x99, 0xac, 0xb6, 0xff, 0x1c, 0x22, 0x54, 0x25, 0xd3,
	0x4e, 0x3b, 0x65, 0xbc, 0x01, 0x2b, 0x89, 0x2a, 0x35, 0x56, 0x12, 0x12, 0x34, 0xef, 0x69, 0x14,
	0x1e, 0x85, 0xf6, 0x2a, 0xff, 0x22, 0x3a, 0x38, 0xae, 0xf8, 0xf2, 0x7d, 0x61, 0xaa, 0x9d, 0x69,
	0xf7, 0xdd, 0x56, 0x95, 0xf7, 0xa5, 0x54, 0xcd, 0xf2, 0x7e, 0xe1, 0xb2, 0x5a, 0x4f, 0xd2, 0xd5,
	0xd5, 0xb2, 0xda, 0x28, 0xbc, 0x85, 0xdd, 0x9c, 0x07, 0x3a, 0xe8, 0xa8, 0x20, 0xde, 0x03, 0x84,
	0x7e, 0xe0, 0xe7, 0x39, 0x84, 0xfe, 0x8b, 0x40, 0x8b, 0x8d, 0xd1, 0x3b, 0xfa, 0x81, 0xe9, 0xe8,
	0x4c, 0x7b, 0xea, 0x94, 0xdf, 0x6a, 0xfd, 0xb0, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58,
	0x66, 0x7d, 0x88, 0x41, 0x01, 0x00, 0x00,
}
